# Generated by Django 3.1.12 on 2025-11-23 21:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(help_text='Numeric command code understood by the ESP32 firmware.')),
                ('param1', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('param2', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('param3', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('param4', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('note', models.CharField(blank=True, help_text='Optional human readable description of the command.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DEVICE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A unique name for the device, e.g., 'Main_Entrance_ESP32'", max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('wifi_signal_strength', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(0)])),
                ('api_key', models.CharField(blank=True, help_text='Secret key for device authentication', max_length=128, null=True, unique=True)),
                ('custom_field_1', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field_2', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field_3', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field_4', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field_5', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'DEVICE',
                'verbose_name_plural': 'DEVICES',
            },
        ),
        migrations.CreateModel(
            name='PERSONAL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'PERSONAL',
                'verbose_name_plural': 'PERSONAL',
            },
        ),
        migrations.CreateModel(
            name='SyslogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.IntegerField(default=6)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_time', models.CharField(blank=True, max_length=64, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('host', models.CharField(max_length=64)),
                ('facility', models.CharField(max_length=64)),
                ('priority', models.IntegerField(choices=[(0, 'EMERG'), (1, 'ALERT'), (2, 'CRIT'), (3, 'ERR'), (4, 'WARNING'), (5, 'NOTICE'), (6, 'INFO'), (7, 'DEBUG')])),
                ('tag', models.CharField(max_length=64)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TAG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('is_allowed', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('encrypted_info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arduino_comm.personal')),
            ],
            options={
                'verbose_name': 'TAG',
                'verbose_name_plural': 'TAGS',
            },
        ),
        migrations.CreateModel(
            name='TagRevokeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arduino_comm.device')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revoke_requests', to='arduino_comm.tag')),
            ],
            options={
                'verbose_name': 'Tag Revoke Request',
                'verbose_name_plural': 'Tag Revoke Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='TagRegisterRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_uid', models.CharField(help_text='Raw UID from RFID/NFC tag', max_length=100)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.CharField(blank=True, help_text='Optional source info (e.g., ESP32, user)', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('associated_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arduino_comm.personal')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arduino_comm.device')),
            ],
            options={
                'verbose_name': 'Tag Registration Request',
                'verbose_name_plural': 'Tag Registration Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='CommandQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_emergency', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('delivered', 'Delivered'), ('acknowledged', 'Acknowledged'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('expires_at', models.DateTimeField(help_text='When the command should automatically expire.')),
                ('enqueued_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('command', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='arduino_comm.command')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_queue', to='arduino_comm.device')),
            ],
            options={
                'ordering': ['-is_emergency', 'enqueued_at'],
            },
        ),
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arduino_comm.command')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arduino_comm.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='command',
            name='device',
            field=models.ForeignKey(help_text='Device that should receive this command', on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='arduino_comm.device'),
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_uid', models.CharField(default='UNKNOWN', help_text='Raw UID of the tag used', max_length=100)),
                ('esp_timestamp', models.CharField(blank=True, help_text='ESP32 local timestamp (as string)', max_length=64, null=True)),
                ('server_timestamp', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('granted', 'Access Granted'), ('denied', 'Access Denied'), ('error', 'Unknown/Error')], default='error', max_length=16)),
                ('details', models.CharField(blank=True, help_text="Details like 'Tag not assigned', 'Access granted to John'", max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_logs', to='arduino_comm.device')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arduino_comm.personal')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='arduino_comm.tag')),
            ],
            options={
                'verbose_name': 'Access Log',
                'verbose_name_plural': 'Access Logs',
                'ordering': ['-server_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SENSOR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sensor', models.CharField(default='UNKNOWN_SENSOR', help_text='Unique sensor ID reported by device', max_length=64)),
                ('type', models.CharField(choices=[('readonly', 'Read-Only'), ('settable', 'Settable')], default='readonly', help_text='Whether sensor is passive (readonly) or can be written to', max_length=16)),
                ('name', models.CharField(help_text='Human-readable sensor name', max_length=100)),
                ('number', models.PositiveIntegerField(blank=True, help_text='Optional pin number or internal reference', null=True)),
                ('status', models.CharField(default='OFFLINE', help_text='Sensor health/status, e.g., OK, OFFLINE, ERROR', max_length=50)),
                ('value_int', models.FloatField(default=-99999, help_text='Primary numeric value (e.g., temperature, state)')),
                ('value_text', models.CharField(blank=True, help_text="Optional textual info (e.g., 'Door open', 'Charging')", max_length=255, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When the server last received an update')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='arduino_comm.device')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
                'unique_together': {('device', 'id_sensor')},
            },
        ),
    ]
