# Generated by Django 3.1.12 on 2025-12-18 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_comm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value_int', models.FloatField()),
                ('value_text', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='OK', max_length=50)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='arduino_comm.sensor')),
            ],
            options={
                'verbose_name': 'Sensor History',
                'verbose_name_plural': 'Sensor Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
