# Generated by Django 4.2.25 on 2025-10-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_comm', '0002_command_commandqueue_commandlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyslogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('host', models.CharField(max_length=64)),
                ('facility', models.CharField(max_length=64)),
                ('priority', models.IntegerField(choices=[(0, 'EMERG'), (1, 'ALERT'), (2, 'CRIT'), (3, 'ERR'), (4, 'WARNING'), (5, 'NOTICE'), (6, 'INFO'), (7, 'DEBUG')])),
                ('tag', models.CharField(max_length=64)),
                ('message', models.TextField()),
            ],
        ),
    ]
