# Generated by Django 4.2.25 on 2025-10-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_comm', '0003_syslogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='syslogentry',
            name='severity',
            field=models.IntegerField(default=6),
        ),
    ]
