# Generated by Django 4.2.25 on 2025-10-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_comm', '0004_syslogentry_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='syslogentry',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
