# Generated by Django 4.2.25 on 2025-10-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_comm', '0005_syslogentry_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syslogentry',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
