# Generated by Django 4.2.25 on 2025-10-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_comm', '0006_alter_syslogentry_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syslogentry',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='syslogentry',
            name='device_time',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
