# Generated by Django 4.2.25 on 2025-10-31 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_comm', '0008_alter_accesslog_options_alter_sensor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagRevokeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arduino_comm.device')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revoke_requests', to='arduino_comm.tag')),
            ],
            options={
                'verbose_name': 'Tag Revoke Request',
                'verbose_name_plural': 'Tag Revoke Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='TagRegisterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_uid', models.CharField(help_text='Raw UID from RFID/NFC tag', max_length=100)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.CharField(blank=True, help_text='Optional source info (e.g., ESP32, user)', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('associated_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arduino_comm.personal')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arduino_comm.device')),
            ],
            options={
                'verbose_name': 'Tag Registration Request',
                'verbose_name_plural': 'Tag Registration Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
