# Generated by Django 4.2.25 on 2025-11-17 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_comm', '0009_tagrevokerequest_tagregisterrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='encrypted_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arduino_comm.personal'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
